#!/bin/bash

### Download KOFAMscan files ##############################
mkdir KOFAM
cd ./KOFAM
## record path to current directory
cwd_my_var=$(pwd)

wget ftp://ftp.genome.jp/pub/db/kofam/ko_list.gz
wget ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz
wget ftp://ftp.genome.jp/pub/tools/kofam_scan/kofam_scan-1.3.0.tar.gz
wget https://www.genome.jp/ftp/tools/kofam_scan/README.md
tar -xf profiles.tar.gz
tar -xf kofam_scan-1.3.0.tar.gz
gunzip ko_list.gz

### edit SOC_mine file #####################################
cd ./kofam_scan-1.3.0/
ks_my_var=$(pwd)
cd ..
cd ..
python_script="SOC_mine.py"
sed -i.bak '86s/.$//' "$python_script"
string_to_add="-p ${cwd_my_var}/profiles/prokaryote.hal -k ${cwd_my_var}/ko_list &"
sed -i.bak '86s/$/\\/' "$python_script"
awk -v new_line="$string_to_add" 'NR==87{$0=new_line}1' "$python_script" > temp && mv temp "$python_script"
chmod +x SOC_mine.py

### Download antiSMASH files ##############################
mkdir ANTISMASH
cd ./ANTISMASH
wget https://dl.secondarymetabolites.org/releases/7.0.0/antismash-7.0.0.tar.gz
tar -zxf antismash-7.0.0.tar.gz
cd ./antismash-7.0.0
as_my_var=$(pwd)
cd ../
pip install ./antismash-7.0.0
python antismash-7.0.0/antismash/download_databases.py

### add things to path #####################################
echo "#################################################"
echo ""
echo "Your path to KOFAMscan is:"
echo ${ks_my_var}
echo ""
echo "Your path1 to antiSMASH is:"
echo ${as_my_var}
echo ""
echo "Your path2 to antiSMASH is:"
echo ${as_my_var}/antismash
echo ""
echo "See the README for instructions on how to add this to your path"
echo ""
echo "#################################################"

## if on mac, use bash_profile
#nano ~/.bash_profile
#export PATH="/path/to/kofam_scan-1.3.0:$PATH"
#export PATH="/path/to/antismash-7.0.0/antismash:$PATH"
#export PATH="/path/to/antismash-7.0.0:$PATH"
## if on linux, use profile
#nano ~/.profile
#export PATH="/path/to/kofam_scan-1.3.0:$PATH"
#export PATH="/path/to/antismash-7.0.0/antismash:$PATH"
#export PATH="/path/to/antismash-7.0.0:$PATH"
